# https://rust-lang.github.io/rustfmt

edition = "2024"

# imports
group_imports = "StdExternalCrate"
imports_granularity = "module"

# comments
comment_width = 120
doc_comment_code_block_width = 120
wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true

format_strings = true
