on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    environment: copilot
    steps:
    - name: Install Rust MCP Server
      run: cargo install --git https://github.com/Vaiz/rust-mcp-server.git --tag stable
